name: Test

on:
  workflow_dispatch:
    inputs:
      target:
        description: Build target
        required: true
        default: all
        type: choice
        options:
          - all
          - windows-x64
          - windows-arm64
          - macos-x64
          - macos-arm64
          - linux-x64-gnu
          - linux-arm64-gnu
          - linux-x64-musl
          - linux-arm64-musl

concurrency:
  group: ${{ github.repository }}-automation
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      target: ${{ inputs.target }}
      release_tag: dev
